version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: langgraphjs-postgres-test
    volumes:
      - ./tmp/integration_tests/pgvector:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
      # Enable logging of connections and disconnections
      POSTGRES_LOG_CONNECTIONS: "on"
      POSTGRES_LOG_DISCONNECTIONS: "on"
      POSTGRES_LOG_MIN_MESSAGES: "info" # Logs messages of level INFO and above
    ports:
      - "5434:5432"

  mysql:
    image: mysql:8.0
    container_name: langgraphjs-mysql-test
    volumes:
      - ./tmp/integration_tests/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
